Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = {'egg':100, 'ham':100}
y = {'ham':300, 'bread':250} 

x | y
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [98][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m x [38;5;241m=[39m {[38;5;124m'[39m[38;5;124megg[39m[38;5;124m'[39m:[38;5;241m100[39m, [38;5;124m'[39m[38;5;124mham[39m[38;5;124m'[39m:[38;5;241m100[39m}
[1;32m      2[0m y [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mham[39m[38;5;124m'[39m:[38;5;241m300[39m, [38;5;124m'[39m[38;5;124mbread[39m[38;5;124m'[39m:[38;5;241m250[39m} 
[0;32m----> 4[0m [43mx[49m[43m [49m[38;5;241;43m|[39;49m[43m [49m[43my[49m

[0;31mTypeError[0m: unsupported operand type(s) for |: 'dict' and 'dict'
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

